name: agricola_core
description: Shared models, API services, and utilities for the Agricola ecosystem.
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ^3.9.0
  flutter: '>=3.9.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  equatable: ^2.0.8
  fpdart: ^1.2.0
  uuid: ^4.5.1
  intl: ^0.20.2
